[build]
  # Directory to publish (relative to root)
  publish = "html"
  
  # Build command (optional - we're pre-generating HTML)
  command = "source venv/bin/activate && python convert_md_to_html.py"

[build.environment]
  # Python version for Netlify
  PYTHON_VERSION = "3.11"

# Redirect rules for clean URLs
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle SPA routing (if needed in future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600"

# Cache static assets longer
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling (if needed in future)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Functions (if needed in future)
[functions]
  directory = "netlify/functions"
